services:
    simple_bus.asynchronous_steroids.event_bus.event_subscribers_collection:
        class: SimpleBus\Message\CallableResolver\CallableCollection
        public: false
        arguments:
            # collection of event subscriber services ids, will be provided by the RegisterSubscribers compiler pas
            - []
            - '@simple_bus.asynchronous.event_bus.callable_resolver'
    simple_bus.asynchronous_steroids.event_bus.event_subscribers_resolver:
        class: SimpleBus\Message\Subscriber\Resolver\NameBasedMessageSubscriberResolver
        public: false
        arguments:
            - '@simple_bus.asynchronous.event_bus.event_name_resolver'
            - '@simple_bus.asynchronous_steroids.event_bus.event_subscribers_collection'